### ISSUE TITLE
Validation Error - Joseph

### ISSUE THREAD

**Issue by jadeclan** [abcd134/JJS3512#1]
Really just testing this feature to see how it works...... I think you know about this error already.

Validation Output: 2 Errors

Error Line 89, Column 98: Start tag a seen in table.
…="../SMovie/SMovie.aspx?movies=122917">The Hobbit: The Battle of the Five Armi…
✉
Error Line 89, Column 98: Cannot recover after last error. Any further errors will be ignored.
…="../SMovie/SMovie.aspx?movies=122917">The Hobbit: The Battle of the Five Armi…

**Comment by abcd134** [comment]
James what page is this?

On Sat, Mar 7, 2015 at 8:41 AM, jadeclan notifications@github.com wrote:

> Assigned #1 https://github.com/abcd134/JJS3512/issues/1 to @abcd134
> https://github.com/abcd134.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abcd134/JJS3512/issues/1#event-248002505.

## 

Joseph Balatbat

**Comment by jadeclan** [comment]
It showed up when I went to validate the HTML on the about page.

**Comment by abcd134** [comment]
No errors here James. Can you push what your working on when you have the
time

**Comment by jadeclan** [comment]
the error shows up when I copy and paste the code to a html validation site.  I pushed my stuff 30 minutes ago.

**Comment by jadeclan** [comment]
when i say code i mean the source view code from the browser

**Comment by abcd134** [comment]
When I ran it to validator.w3.org the only problem I ran into was that it
wasn't HTML 4 valid

**Comment by jadeclan** [comment]
lol good job fixing the errror :-)

On Sat, Mar 7, 2015 at 10:11 AM, abcd134 notifications@github.com wrote:

> When I ran it to validator.w3.org the only problem I ran into was that it
> wasn't HTML 4 valid
> On Mar 7, 2015 9:55 AM, "jadeclan" notifications@github.com wrote:
> 
> > when i say code i mean the source view code
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/abcd134/JJS3512/issues/1#issuecomment-77697912.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abcd134/JJS3512/issues/1#issuecomment-77698758.

## 

Proud supporter of the Calgary Food Bank
www.calgaryfoodbank.com

**Comment by abcd134** [comment]
Uhm...I didn't do anything

**Comment by jadeclan** [comment]
I am doing something else now, I will try to replicate the error later and
let you know.  It'll take me a couple of hours to get back to it.  How do
you like how the about page is progressing?

On Sat, Mar 7, 2015 at 10:27 AM, abcd134 notifications@github.com wrote:

> Uhm...I didn't do anything
> On Mar 7, 2015 10:24 AM, "jadeclan" notifications@github.com wrote:
> 
> > lol good job fixing the errror :-)
> > 
> > On Sat, Mar 7, 2015 at 10:11 AM, abcd134 notifications@github.com
> > wrote:
> > 
> > > When I ran it to validator.w3.org the only problem I ran into was that
> > > it
> > > wasn't HTML 4 valid
> > > On Mar 7, 2015 9:55 AM, "jadeclan" notifications@github.com wrote:
> > > 
> > > > when i say code i mean the source view code
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/abcd134/JJS3512/issues/1#issuecomment-77697912.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/abcd134/JJS3512/issues/1#issuecomment-77698758.
> > 
> > ## 
> > 
> > Proud supporter of the Calgary Food Bank
> > www.calgaryfoodbank.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/abcd134/JJS3512/issues/1#issuecomment-77699375.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abcd134/JJS3512/issues/1#issuecomment-77699510.

## 

Proud supporter of the Calgary Food Bank
www.calgaryfoodbank.com

**Comment by abcd134** [comment]
I LOVE IT.  "joie de vivre" <- IM GONNA USE THAT QUOTE. Do I have to pay
royalties?
 :3

On Sat, Mar 7, 2015 at 10:29 AM, jadeclan notifications@github.com wrote:

> I am doing something else now, I will try to replicate the error later and
> let you know. It'll take me a couple of hours to get back to it. How do
> you like how the about page is progressing?
> 
> On Sat, Mar 7, 2015 at 10:27 AM, abcd134 notifications@github.com wrote:
> 
> > Uhm...I didn't do anything
> > On Mar 7, 2015 10:24 AM, "jadeclan" notifications@github.com wrote:
> > 
> > > lol good job fixing the errror :-)
> > > 
> > > On Sat, Mar 7, 2015 at 10:11 AM, abcd134 notifications@github.com
> > > wrote:
> > > 
> > > > When I ran it to validator.w3.org the only problem I ran into was
> > > > that
> > > > it
> > > > wasn't HTML 4 valid
> > > > On Mar 7, 2015 9:55 AM, "jadeclan" notifications@github.com wrote:
> > > > 
> > > > > when i say code i mean the source view code
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/abcd134/JJS3512/issues/1#issuecomment-77697912
> > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/abcd134/JJS3512/issues/1#issuecomment-77698758.
> > > 
> > > ## 
> > > 
> > > Proud supporter of the Calgary Food Bank
> > > www.calgaryfoodbank.com
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/abcd134/JJS3512/issues/1#issuecomment-77699375.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/abcd134/JJS3512/issues/1#issuecomment-77699510.
> 
> ## 
> 
> Proud supporter of the Calgary Food Bank
> www.calgaryfoodbank.com
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abcd134/JJS3512/issues/1#issuecomment-77699636.

## 

Joseph Balatbat

**Comment by jadeclan** [comment]
When I run the about or error pages, then view the source in the browser, and then select all and copy, go to W3C validator and paste, W3C says there are two errors starting with the line showing the first movie.   As far as I can tell, it has no impact and maybe it's just a W3C validation weirdness.  Don't worry about it, I'll show you on Monday if it's still there.
