### ISSUE TITLE
Some small things (capturing them when I see them -- add when you see stuff)

### ISSUE THREAD

**Issue by jadeclan** [abcd134/JJS3512#15]
Delete when you have either dealt with the issue or decided not to.

Default page -- 5 feature movie button looks weird
Default page -- there is a dash in front of the actors birthdates (easy fix)  *****\* DONE ******
About Page -- in page links don't work  *****\* My bad ********
site master cs and browse.cs -- need to clean up filter/search code
should we add a scroll bar to the browse page for the movie listings? ******\* Done *******

**Comment by abcd134** [comment]
_Bump_ is this still valid
