### ISSUE TITLE
Master change log line numbers

### ISSUE THREAD

**Issue by jadeclan** [abcd134/JJS3512#2]
Last night, within an hour we all made changes to the master change log file.... looks like Sonia tried to commit a  master change log file from an older (pre my/joseph updates) log file, so her line numbers overlap. I think Sonia needs to take a copy of her changes to the master log, delete them from her master log, synch and then add her changes to the new master log. 
I don't think I can see either of your changes until this is done.

**Comment by abcd134** [comment]
OK. New rule. Before your post a change. Make sure you pull/fetch changes
first. To retrieve latest version

**Comment by abcd134** [comment]
This prevent the kitty cats from fighting over the cat food . they a get
their turns

**Comment by jadeclan** [comment]
lol

On Sat, Mar 14, 2015 at 8:57 AM, abcd134 notifications@github.com wrote:

> This prevent the kitty cats from fighting over the cat food . they a get
> their turns
> 
> On Mar 14, 2015 7:18 AM, "jadeclan" notifications@github.com wrote:
> 
> > Last night, within an hour we all made changes to the master change log
> > file.... looks like Sonia tried to commit a master change log file from
> > an
> > older (pre my/joseph updates) log file, so her line numbers overlap. I
> > think Sonia needs to take a copy of her changes to the master log, delete
> > them from her master log, synch and then add her changes to the new
> > master
> > log.
> > I don't think I can see either of your changes until this is done.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/abcd134/JJS3512/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abcd134/JJS3512/issues/2#issuecomment-80522700.

## 

Proud supporter of the Calgary Food Bank
www.calgaryfoodbank.com

**Comment by jadeclan** [comment]
ps from default you can now filter by genre.

On Sat, Mar 14, 2015 at 8:58 AM, James Bergeron jameslbergeron@gmail.com
wrote:

> lol
> 
> On Sat, Mar 14, 2015 at 8:57 AM, abcd134 notifications@github.com wrote:
> 
> > This prevent the kitty cats from fighting over the cat food . they a get
> > their turns
> > 
> > On Mar 14, 2015 7:18 AM, "jadeclan" notifications@github.com wrote:
> > 
> > > Last night, within an hour we all made changes to the master change log
> > > file.... looks like Sonia tried to commit a master change log file from
> > > an
> > > older (pre my/joseph updates) log file, so her line numbers overlap. I
> > > think Sonia needs to take a copy of her changes to the master log,
> > > delete
> > > them from her master log, synch and then add her changes to the new
> > > master
> > > log.
> > > I don't think I can see either of your changes until this is done.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/abcd134/JJS3512/issues/2.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/abcd134/JJS3512/issues/2#issuecomment-80522700.
> 
> ## 
> 
> Proud supporter of the Calgary Food Bank
> www.calgaryfoodbank.com

## 

Proud supporter of the Calgary Food Bank
www.calgaryfoodbank.com

**Comment by abcd134** [comment]
Ok. Is this resolved?
