### ISSUE TITLE
Scrolling under the Header on the browse page

### ISSUE THREAD

**Issue by jadeclan** [abcd134/JJS3512#3]
Haven't had time to look into this.  suspect it's a css issue, but no idea how to resolve without spending time on it.

**Comment by abcd134** [comment]
-blank

**Comment by jadeclan** [comment]
Resolved.  See .anchor css in the site.css file..... included an empty span (with an anchor class) above the place I needed to go with an in page reference.  works like a charm.  Tested on the 10 in page links on the About Page.
