### ISSUE TITLE
Image under header on home page

### ISSUE THREAD

**Issue by jadeclan** [abcd134/JJS3512#6]
apply the .anchor fix to have your full movie picture seen (right now you have 100px cut off)
using this as a reminder note.  Mark it resolved when you are happy with the look.

The fix ----- 
add an empty span above where you put in the carousel.  Put class=anchor inside the empty span.  See site.css file (at bottom) for what the class does.

**Comment by abcd134** [comment]
.anchor-default was created to address this issue.
Change:
Increased height from 100 to 150px
